### ISSUE TITLE
Power Off doesn't work

### ISSUE THREAD

**Issue by DoctorZIP** [kairen/maas-wakeonlan-driver#3]
Hi, 
Thank you for your work on this driver. Powering On working fine, but after power off stops working. Maybe it is any chance to move Manual poweroff functionality to this driver?

Thanks!

**Comment by kairen** [comment]
Hi, @DoctorZIP The WoL power driver only support power-on because of the WoL only to wake! Maybe you can try IPMI(or other drivers) to manage the machines.

**Comment by DoctorZIP** [comment]
I thought the main idea of this driver is ability to manipulate with old or not server-class motherboards, but after using this driver I can't to poweroff/reboot my PCs. So I can poweron but can't poweroff. Strange as for me. Maybe you have some ideas how to include poweroff functionality form Manual mode?
